# Generated by Django 3.0.6 on 2020-06-01 12:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_mac_address', models.CharField(max_length=25, unique=True)),
                ('device_type', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('fingerprint', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_fingerprint', to='DeviceFingerprint.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet', models.TextField(default='')),
                ('packet_time', models.DecimalField(decimal_places=32, default=0.0, max_digits=32)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_set', to='DeviceFingerprint.Device')),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_fingerprint', to='DeviceFingerprint.Device')),
            ],
        ),
    ]
