# Generated by Django 3.0.6 on 2020-06-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceFingerprint', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packet',
            new_name='PacketData',
        ),
    ]
