# Generated by Django 3.0.3 on 2020-06-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceFingerprint', '0002_auto_20200601_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetdata',
            name='field_name',
            field=models.TimeField(auto_now=True),
        ),
    ]
