# Generated by Django 3.0.3 on 2020-06-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceFingerprint', '0006_auto_20200620_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetdata',
            name='packet_time',
            field=models.DecimalField(decimal_places=32, default=0.0, max_digits=64),
        ),
    ]
