# Generated by Django 3.0.3 on 2020-06-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceFingerprint', '0007_auto_20200620_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packetdata',
            name='arrival_time',
        ),
    ]
